### ISSUE TITLE
Docs: add an awesome logo! 

### ISSUE THREAD

**Issue by AndreVarandas** [FranAmorim/teatime#12]
We need a cool logo, use your imagination! 😎

**Comment by xcyberpunkx0** [comment]
![teatime](https://user-images.githubusercontent.com/53346087/66492285-c246e000-ead1-11e9-8627-a64f191984ae.jpg)

**Comment by thehashton** [comment]
Added it in a PR to the readme + did some linting :)
https://github.com/FranAmorim/teatime/pull/17

**Comment by AndreVarandas** [comment]
We added @xcyberpunkx0 but we are also thankfull for all the other suggestions, thank you all!
