### ISSUE TITLE
bug: Wrong property type

### ISSUE THREAD

**Issue by AndreVarandas** [FranAmorim/teatime#24]
Shouldn't this be and array instead? 

https://github.com/FranAmorim/teatime/blob/d1b9aa35491628ec9e48134697157cc288268b9d/src/index.js#L5

**Comment by FranAmorim** [comment]
Can be.
Instead of:
```javascript
this.jobs[name] = {
      time,
      action: this.setJob(name, time, method),
};
```
We can do:
```javascript
this.jobs.push({
      name
      time,
      action: this.setJob(name, time, method),
});
```
But that means, when you try to get the job we will need to use a find
```javascript
return this.jobs.find(item => item.name === name);
```
If Object:
```javascript
return this.jobs[name]
```
Thats the reason for the Object.

Which one would you use?

EDIT: Replace filter to find. Name should be unique.

**Comment by AndreVarandas** [comment]
I prefer the second option as:

```javascript
this.jobs.push({
      name
      time,
      action: this.setJob(name, time, method),
});
```

But, regardless it seems the initialization is wrong, and should be:

```javascript
this.jobs = []
```

**Comment by FranAmorim** [comment]
For the current implementation the initialisation is correct.
We will never need to iterate the jobs, for that reason we will use object.
