### ISSUE TITLE
Bug: Wrong class name

### ISSUE THREAD

**Issue by AndreVarandas** [FranAmorim/teatime#3]
The name of the package is TeaTime, but the named class is TieTime. 😄 

https://github.com/FranAmorim/teatime/blob/400d175b0039ad76326195a101a4ea91c49ae182/src/index.js#L1

**Comment by TomLandis** [comment]
can i take this issue?

**Comment by AndreVarandas** [comment]
Thank you for the contribution @TomLandis !

Closed with #6
