### ISSUE TITLE
Docs: Update documentation

### ISSUE THREAD

**Issue by AndreVarandas** [FranAmorim/teatime#30]
Readme.md file specification is not up to date. 
Methods like this one below are not yet listed on the specification. 

https://github.com/FranAmorim/teatime/blob/570df41bba71b48b1b6ec938b89ae80505d2879c/src/index.js#L34

File should be updated, renaming methods that have been changed and adding the new ones.

#### Methods:
| Methods       | Description                                     | Ready |
| ------------- |:------------------------------------------------|:-----:|
| addJob()      | Used to create a Job                            |   ✓   |
| stopJob()     | Stops a Job but doesn't remove from the manager |   ✓   |
| deleteJob()  | Removes a Job from the Manager        |   ✓   |
| MISSING | Missing        |   x   |
| MISSING | Missing        |   x   |

**Comment by AndreVarandas** [comment]
We basically need to include setJob() and restartJob() with a small description. (to the table above) All are ready to go.

**Comment by clussell** [comment]
Can I take this one?

**Comment by sarathkumar6** [comment]
@AndreVarandas I've added JSDoc to the methods in the index.js and finished up the ReadMe. Please have a look at it when you find time. Thanks.
https://github.com/FranAmorim/teatime/pull/31

**Comment by AndreVarandas** [comment]
Hi guys and thank you for your time. I’m accepting @sarathkumar6 changes. 😊

**Comment by AndreVarandas** [comment]
Closed with #31 thanks guys!
