### ISSUE TITLE
Feat: Add eslint

### ISSUE THREAD

**Issue by AndreVarandas** [FranAmorim/teatime#7]
- We want to use eslint [Airbnb config](https://www.npmjs.com/package/eslint-config-airbnb).

Todo:
- eslintrc file is added to the project.
- eslint is added to the dev-dependencies.

**Comment by wrillrysata** [comment]
Hi @AndreVarandas, any assignee yet for this task? If none, I'll like to take it up

**Comment by aravindh-nagarajan** [comment]
Hey Sorry, forgot to ask to get assigned. Just raised PR for this https://github.com/FranAmorim/teatime/pull/8

**Comment by AndreVarandas** [comment]
Thanks for the help guys,

We will accept your help @aravindh-nagarajan 👍

**Comment by AndreVarandas** [comment]
Closed with #8 - Thanks for your help! 🚀
